### PR TITLE
Branch david mcbee

### PR DESCRIPTION
**Pull request by davidmcbee**
To merge the following:
1. Adding ARIMA model
2.  Changes to readme to describe ARIMA model
3.  images for readme description

### CODE REVIEW

**Review by amelinn9 — APPROVED** [review]
Looks good, David!

**Review by bksuro — APPROVED** [review]
Looks good.

**Comment by AndrejaCH** [comment]
Very thorough description! Looks great!

**Review by AndrejaCH — APPROVED** [review]
Very thorough description! Looks great!

**Pull request merged**
